# Generated by Django 4.2.4 on 2023-08-26 12:49

import appname.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, null=True, upload_to=appname.models.get_image_path)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
